### ISSUE TITLE
In VS2017, having UFUNCTION() above a function prevents me from typing the trailing ;

### ISSUE THREAD

**Issue by DamirHalilovic** [hackalyze/ue4-vs-extensions#13]
As the title suggests, having something like this:

UFUNCTION()
void SomeFun()

...and typing ; in the end, nothing would happen. Disabling the extension it works as intended.

Thanks again for extension, hopefully this isn't a huge issue to fix!

**Comment by hackalyze** [comment]
Sorry for taking so long to respond, I thought this was going to be specific to VS2017 since I couldn't repro in 2015.  I just got VS2017 community edition installed and still can't repro.  Have you maybe customized your VS options?  This might happen if you've disabled "Automatically format statement when I type a ";".

**Comment by DamirHalilovic** [comment]
Hey hackalyze,

I've made a video showing the issue: https://youtu.be/QOg1I_r2gC0

Note how the ; appears in the function parenthesis near the top, and how the comment on the following line gets highlighted.

That being said - you are right, "Automatically format statement when I type a ";"" was turned off, although it wasn't me who did it, it seems that 2017 did some weird stuff to my default settings.

Best regards,
Damir H.

**Comment by hackalyze** [comment]
I just pushed up a potential fix to the branch here: https://github.com/hackalyze/ue4-vs-extensions/tree/check-autoformat-on-semicolons

This will disable the formatting fixes if that option is turned off.  Let me know if that does the trick for you.
